# Base configs
baseurl: "https://photos.mobeigi.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-41ZEE01DTM"
exclude: ["images/raws"]

# UI configs
title: "Lens of Mo Beigi"
subtitle: "Photography & Colouring"
author: "Mo Beigi"
email: "me@mobeigi.com"
header:
 title: "Lens of"
 subtitle: "Mo Beigi"
footer:
 name: "Hi, I'm Mo"
 bio: "I am a photography and colouring hobbyist."
 github: ""
social_urls:
  facebook: null
  twitter: null
  instagram: "https://www.instagram.com/lensofmobeigi"
  dribbble: null
  linkedin: null
  github: null
